# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b5eb9b07899ef0d323db9df85c33b9aee7f882ba8f38666f515863370a98c552fb388eb77866f610c025eb5d1601eb6e9a2cb4121373ca976be080d0ec38d7c

test:
  secret_key_base: 27ac1a36d859c5e540a2fa69029c2fe465d8171cb57d2acbed17dde1a67e490bb7b7a8f29a84779dc5975d64b3112b0abd03db91ed37e498c9b7ff51ecfe7792

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
